# Generated by Django 2.2.7 on 2019-11-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('sessionid', models.IntegerField(primary_key=True, serialize=False)),
                ('wechatid', models.CharField(max_length=128)),
                ('vip_type', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=16)),
                ('cn_surname', models.CharField(max_length=16)),
                ('cn_name', models.CharField(max_length=32)),
                ('en_first', models.CharField(max_length=32)),
                ('en_other', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=8)),
                ('hkid', models.CharField(max_length=32)),
                ('hkid_path', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=320)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=256)),
                ('edu_level', models.CharField(max_length=32)),
                ('total_working_years', models.CharField(max_length=32)),
                ('signature_path', models.CharField(max_length=128)),
                ('if_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('company', models.CharField(max_length=64)),
                ('occupation', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=32)),
                ('proof_path', models.CharField(max_length=128)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Recommander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=32)),
                ('othername', models.CharField(max_length=64)),
                ('vipid', models.CharField(max_length=32)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
        migrations.CreateModel(
            name='ProfExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_org', models.CharField(max_length=64)),
                ('prof_name', models.CharField(max_length=64)),
                ('prof_date', models.CharField(max_length=32)),
                ('prof_path', models.CharField(max_length=128)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
        migrations.CreateModel(
            name='EduExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_org', models.CharField(max_length=64)),
                ('grad_date', models.DateField()),
                ('edu_maj', models.CharField(max_length=64)),
                ('maj_path', models.CharField(max_length=128)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
    ]
